config/routes.rb
Rails.application.routes.draw do
  root 'expenses#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :expenses, only: [:index, :create, :update, :destroy]
  resources :users, only: [:create, :update]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user

  validates :name, :amount, :transaction_type, presence: true
  validates :amount, numericality: {greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :expenses

  mount_uploader :csv, CsvParserUploader

  validates :first_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    if current_user
      respond_to do |format|
        format.html
        format.json do
          @expenses = current_user.expenses.order(id: :asc).all
        end
      end
    else
      redirect_to '/login'
    end
  end

  def create
    @expense = current_user.expenses.new(expense_params)
    respond_to do |format|
      if @expense.save
        format.json { render json: {}, status: 200}
      else
        format.json { render json: @expense.errors, status: 422 }
      end
    end
  end

  def update
    @expense = get_expense
    respond_to do |format|
      if @expense.update_attributes(expense_params)
        format.json { render json: {}, status: 202 }
      else
        format.json { render json: @expense.errors, status: 422 }
      end
    end
  end

  def destroy
    @expense = get_expense
    @expense.destroy
    respond_to do |format|
      format.json { render json: {}, status: 200 }
    end
  end


  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :transaction_type, :transaction_date)
  end

  def get_expense
    current_user.expenses.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to "/login"
      end
  end

  def update
    @user = get_user
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.json { render json: {}, status: 202 }
      else
        format.json { render json: @user.errors, status: 422 }
      end
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone_number)
  end

  def get_user
    User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/index.html.erb
<div data-js="expenses">
</div>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if (current_user) %>
          <li><%= link_to "Logout", logout_path %></li>
          <li>
            <div class="react-login" data-js="users" data-login="welcome">
            </div>
        </li>
      <% else %>
        <li><%= link_to "Signup", signup_path %></li>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackinDollaz</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato',  media: 'text/css' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>

    <%= yield %>

    <%= javascript_include_tag 'application' %>

    <!-- google-analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-67511397-3', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, url: {action: "create"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= f.label       :First_name %>
    <%= f.text_field  :first_name %>
  </div>
  <div>
    <%= f.label       :Last_name %>
    <%= f.text_field  :last_name %>
  </div>
  <div>
    <%= f.label       :Phone_number %>
    <%= f.text_field  :phone_number %>
  </div>
  <div>
    <%= f.label       :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label           :password %>
    <%= f.password_field  :password %>
  </div>
  <div>
    <%= f.label           :confirmation %>
    <%= f.password_field  :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>